// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/seanrmurphy/vugu-tdl-swagger/swagger/client/c_o_r_s"
	"github.com/seanrmurphy/vugu-tdl-swagger/swagger/client/developers"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "virtserver.swaggerhub.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/seanrm/todo-api/1.0.0"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new simple todo API secure HTTP client.
func New(c Config) *SimpleTodoAPISecure {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(SimpleTodoAPISecure)
	cli.Transport = transport
	cli.CORS = c_o_r_s.New(transport, strfmt.Default, c.AuthInfo)
	cli.Developers = developers.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// SimpleTodoAPISecure is a client for simple todo API secure
type SimpleTodoAPISecure struct {
	CORS       *c_o_r_s.Client
	Developers *developers.Client
	Transport  runtime.ClientTransport
}
