// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the c o r s client
type API interface {
	// OptionsTodo cs o r s support
	// Enable CORS by returning correct headers
	OptionsTodo(ctx context.Context, params *OptionsTodoParams) (*OptionsTodoOK, error)
	// OptionsTodoTodoid cs o r s support
	// Enable CORS by returning correct headers
	OptionsTodoTodoid(ctx context.Context, params *OptionsTodoTodoidParams) (*OptionsTodoTodoidOK, error)
}

// New creates a new c o r s API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for c o r s API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
OptionsTodo cs o r s support

Enable CORS by returning correct headers
*/
func (a *Client) OptionsTodo(ctx context.Context, params *OptionsTodoParams) (*OptionsTodoOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OptionsTodo",
		Method:             "OPTIONS",
		PathPattern:        "/todo",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OptionsTodoReader{formats: a.formats},
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OptionsTodoOK), nil

}

/*
OptionsTodoTodoid cs o r s support

Enable CORS by returning correct headers
*/
func (a *Client) OptionsTodoTodoid(ctx context.Context, params *OptionsTodoTodoidParams) (*OptionsTodoTodoidOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "OptionsTodoTodoid",
		Method:             "OPTIONS",
		PathPattern:        "/todo/{todoid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &OptionsTodoTodoidReader{formats: a.formats},
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*OptionsTodoTodoidOK), nil

}
