// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsTodoParams creates a new OptionsTodoParams object
// with the default values initialized.
func NewOptionsTodoParams() *OptionsTodoParams {

	return &OptionsTodoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsTodoParamsWithTimeout creates a new OptionsTodoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsTodoParamsWithTimeout(timeout time.Duration) *OptionsTodoParams {

	return &OptionsTodoParams{

		timeout: timeout,
	}
}

// NewOptionsTodoParamsWithContext creates a new OptionsTodoParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsTodoParamsWithContext(ctx context.Context) *OptionsTodoParams {

	return &OptionsTodoParams{

		Context: ctx,
	}
}

// NewOptionsTodoParamsWithHTTPClient creates a new OptionsTodoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsTodoParamsWithHTTPClient(client *http.Client) *OptionsTodoParams {

	return &OptionsTodoParams{
		HTTPClient: client,
	}
}

/*OptionsTodoParams contains all the parameters to send to the API endpoint
for the options todo operation typically these are written to a http.Request
*/
type OptionsTodoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options todo params
func (o *OptionsTodoParams) WithTimeout(timeout time.Duration) *OptionsTodoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options todo params
func (o *OptionsTodoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options todo params
func (o *OptionsTodoParams) WithContext(ctx context.Context) *OptionsTodoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options todo params
func (o *OptionsTodoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options todo params
func (o *OptionsTodoParams) WithHTTPClient(client *http.Client) *OptionsTodoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options todo params
func (o *OptionsTodoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsTodoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
