// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOptionsTodoTodoidParams creates a new OptionsTodoTodoidParams object
// with the default values initialized.
func NewOptionsTodoTodoidParams() *OptionsTodoTodoidParams {
	var ()
	return &OptionsTodoTodoidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsTodoTodoidParamsWithTimeout creates a new OptionsTodoTodoidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOptionsTodoTodoidParamsWithTimeout(timeout time.Duration) *OptionsTodoTodoidParams {
	var ()
	return &OptionsTodoTodoidParams{

		timeout: timeout,
	}
}

// NewOptionsTodoTodoidParamsWithContext creates a new OptionsTodoTodoidParams object
// with the default values initialized, and the ability to set a context for a request
func NewOptionsTodoTodoidParamsWithContext(ctx context.Context) *OptionsTodoTodoidParams {
	var ()
	return &OptionsTodoTodoidParams{

		Context: ctx,
	}
}

// NewOptionsTodoTodoidParamsWithHTTPClient creates a new OptionsTodoTodoidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOptionsTodoTodoidParamsWithHTTPClient(client *http.Client) *OptionsTodoTodoidParams {
	var ()
	return &OptionsTodoTodoidParams{
		HTTPClient: client,
	}
}

/*OptionsTodoTodoidParams contains all the parameters to send to the API endpoint
for the options todo todoid operation typically these are written to a http.Request
*/
type OptionsTodoTodoidParams struct {

	/*Todoid
	  Id of todo to get

	*/
	Todoid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the options todo todoid params
func (o *OptionsTodoTodoidParams) WithTimeout(timeout time.Duration) *OptionsTodoTodoidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options todo todoid params
func (o *OptionsTodoTodoidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options todo todoid params
func (o *OptionsTodoTodoidParams) WithContext(ctx context.Context) *OptionsTodoTodoidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options todo todoid params
func (o *OptionsTodoTodoidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options todo todoid params
func (o *OptionsTodoTodoidParams) WithHTTPClient(client *http.Client) *OptionsTodoTodoidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options todo todoid params
func (o *OptionsTodoTodoidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTodoid adds the todoid to the options todo todoid params
func (o *OptionsTodoTodoidParams) WithTodoid(todoid string) *OptionsTodoTodoidParams {
	o.SetTodoid(todoid)
	return o
}

// SetTodoid adds the todoid to the options todo todoid params
func (o *OptionsTodoTodoidParams) SetTodoid(todoid string) {
	o.Todoid = todoid
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsTodoTodoidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param todoid
	if err := r.SetPathParam("todoid", o.Todoid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
