// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/seanrmurphy/vugu-tdl-swagger/swagger/models"
)

// NewAddTodoParams creates a new AddTodoParams object
// with the default values initialized.
func NewAddTodoParams() *AddTodoParams {
	var ()
	return &AddTodoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddTodoParamsWithTimeout creates a new AddTodoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddTodoParamsWithTimeout(timeout time.Duration) *AddTodoParams {
	var ()
	return &AddTodoParams{

		timeout: timeout,
	}
}

// NewAddTodoParamsWithContext creates a new AddTodoParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddTodoParamsWithContext(ctx context.Context) *AddTodoParams {
	var ()
	return &AddTodoParams{

		Context: ctx,
	}
}

// NewAddTodoParamsWithHTTPClient creates a new AddTodoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddTodoParamsWithHTTPClient(client *http.Client) *AddTodoParams {
	var ()
	return &AddTodoParams{
		HTTPClient: client,
	}
}

/*AddTodoParams contains all the parameters to send to the API endpoint
for the add todo operation typically these are written to a http.Request
*/
type AddTodoParams struct {

	/*Todo
	  todo item to add

	*/
	Todo *models.Todo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add todo params
func (o *AddTodoParams) WithTimeout(timeout time.Duration) *AddTodoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add todo params
func (o *AddTodoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add todo params
func (o *AddTodoParams) WithContext(ctx context.Context) *AddTodoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add todo params
func (o *AddTodoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add todo params
func (o *AddTodoParams) WithHTTPClient(client *http.Client) *AddTodoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add todo params
func (o *AddTodoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTodo adds the todo to the add todo params
func (o *AddTodoParams) WithTodo(todo *models.Todo) *AddTodoParams {
	o.SetTodo(todo)
	return o
}

// SetTodo adds the todo to the add todo params
func (o *AddTodoParams) SetTodo(todo *models.Todo) {
	o.Todo = todo
}

// WriteToRequest writes these params to a swagger request
func (o *AddTodoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Todo != nil {
		if err := r.SetBodyParam(o.Todo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
