// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddTodoReader is a Reader for the AddTodo structure.
type AddTodoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddTodoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddTodoCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddTodoBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewAddTodoConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddTodoCreated creates a AddTodoCreated with default headers values
func NewAddTodoCreated() *AddTodoCreated {
	return &AddTodoCreated{}
}

/*AddTodoCreated handles this case with default header values.

item created
*/
type AddTodoCreated struct {
}

func (o *AddTodoCreated) Error() string {
	return fmt.Sprintf("[POST /todo][%d] addTodoCreated ", 201)
}

func (o *AddTodoCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddTodoBadRequest creates a AddTodoBadRequest with default headers values
func NewAddTodoBadRequest() *AddTodoBadRequest {
	return &AddTodoBadRequest{}
}

/*AddTodoBadRequest handles this case with default header values.

invalid input, object invalid
*/
type AddTodoBadRequest struct {
}

func (o *AddTodoBadRequest) Error() string {
	return fmt.Sprintf("[POST /todo][%d] addTodoBadRequest ", 400)
}

func (o *AddTodoBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddTodoConflict creates a AddTodoConflict with default headers values
func NewAddTodoConflict() *AddTodoConflict {
	return &AddTodoConflict{}
}

/*AddTodoConflict handles this case with default header values.

an existing item already exists
*/
type AddTodoConflict struct {
}

func (o *AddTodoConflict) Error() string {
	return fmt.Sprintf("[POST /todo][%d] addTodoConflict ", 409)
}

func (o *AddTodoConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
