// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteTodoParams creates a new DeleteTodoParams object
// with the default values initialized.
func NewDeleteTodoParams() *DeleteTodoParams {
	var ()
	return &DeleteTodoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTodoParamsWithTimeout creates a new DeleteTodoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteTodoParamsWithTimeout(timeout time.Duration) *DeleteTodoParams {
	var ()
	return &DeleteTodoParams{

		timeout: timeout,
	}
}

// NewDeleteTodoParamsWithContext creates a new DeleteTodoParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteTodoParamsWithContext(ctx context.Context) *DeleteTodoParams {
	var ()
	return &DeleteTodoParams{

		Context: ctx,
	}
}

// NewDeleteTodoParamsWithHTTPClient creates a new DeleteTodoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteTodoParamsWithHTTPClient(client *http.Client) *DeleteTodoParams {
	var ()
	return &DeleteTodoParams{
		HTTPClient: client,
	}
}

/*DeleteTodoParams contains all the parameters to send to the API endpoint
for the delete todo operation typically these are written to a http.Request
*/
type DeleteTodoParams struct {

	/*Todoid
	  Id of todo to get

	*/
	Todoid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete todo params
func (o *DeleteTodoParams) WithTimeout(timeout time.Duration) *DeleteTodoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete todo params
func (o *DeleteTodoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete todo params
func (o *DeleteTodoParams) WithContext(ctx context.Context) *DeleteTodoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete todo params
func (o *DeleteTodoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete todo params
func (o *DeleteTodoParams) WithHTTPClient(client *http.Client) *DeleteTodoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete todo params
func (o *DeleteTodoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTodoid adds the todoid to the delete todo params
func (o *DeleteTodoParams) WithTodoid(todoid string) *DeleteTodoParams {
	o.SetTodoid(todoid)
	return o
}

// SetTodoid adds the todoid to the delete todo params
func (o *DeleteTodoParams) SetTodoid(todoid string) {
	o.Todoid = todoid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTodoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param todoid
	if err := r.SetPathParam("todoid", o.Todoid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
