// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllTodosParams creates a new GetAllTodosParams object
// with the default values initialized.
func NewGetAllTodosParams() *GetAllTodosParams {

	return &GetAllTodosParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTodosParamsWithTimeout creates a new GetAllTodosParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllTodosParamsWithTimeout(timeout time.Duration) *GetAllTodosParams {

	return &GetAllTodosParams{

		timeout: timeout,
	}
}

// NewGetAllTodosParamsWithContext creates a new GetAllTodosParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllTodosParamsWithContext(ctx context.Context) *GetAllTodosParams {

	return &GetAllTodosParams{

		Context: ctx,
	}
}

// NewGetAllTodosParamsWithHTTPClient creates a new GetAllTodosParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllTodosParamsWithHTTPClient(client *http.Client) *GetAllTodosParams {

	return &GetAllTodosParams{
		HTTPClient: client,
	}
}

/*GetAllTodosParams contains all the parameters to send to the API endpoint
for the get all todos operation typically these are written to a http.Request
*/
type GetAllTodosParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all todos params
func (o *GetAllTodosParams) WithTimeout(timeout time.Duration) *GetAllTodosParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all todos params
func (o *GetAllTodosParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all todos params
func (o *GetAllTodosParams) WithContext(ctx context.Context) *GetAllTodosParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all todos params
func (o *GetAllTodosParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all todos params
func (o *GetAllTodosParams) WithHTTPClient(client *http.Client) *GetAllTodosParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all todos params
func (o *GetAllTodosParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTodosParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
